In [1]:
import pandas as pd
import sys, os
import re
import numpy as np
sys.path.insert(0, os.path.abspath('..'))
from project.preparation.vdrive_to_mtex import VdriveToMtex

# How it works 

## Step by step

In [2]:
vdrive_filename = '../tests/data/my_ducu.txt'
assert os.path.exists(vdrive_filename)

Initialize object 

In [3]:
o_handler = VdriveToMtex(vdrive_handler_file=vdrive_filename)

Load data

In [4]:
o_handler.load()

In [5]:
data = o_handler.raw_data
data.head()

#psi  phi  I/V_Ni111_1  I/V_Ni200_1  I/V_Ni220_1  I/V_Ni311_1  I/V_Ni222_1  \
0     0    0     0.812640     1.452050     0.711520     0.927503     0.809388   
1     5   30     0.702029     1.727361     0.604477     0.795381     0.681152   
2     5   60     0.660330     1.848286     0.644271     0.809338     0.669732   
3     5   90     0.733149     1.759387     0.777081     0.772522     0.779609   
4     5  120     0.782842     1.565342     0.704357     0.755036     0.771645   

   I/V_Ni400_1  I/V_Ni331_1  I/V_Ni420_1  I/V_Ni422_1  I/V_Ni511_1  
0     1.424946     0.601256     0.699247     0.637840     1.009798  
1     1.705310     0.636809     0.706412     0.791649     0.879390  
2     1.871940     0.581240     0.743365     0.701569     1.132545  
3     1.789216     0.569585     0.776940     0.805704     1.133505  
4     1.512697     0.567696     0.684586     0.768479     1.062074

sort the data

In [6]:
o_handler.sort_raw_data()
data_sorted = o_handler.raw_data_sorted
data_sorted.head()

#psi  phi  I/V_Ni111_1  I/V_Ni200_1  I/V_Ni220_1  I/V_Ni311_1  \
0      0    0     0.812640     1.452050     0.711520     0.927503   
12     5    0     0.842873     1.524866     0.630656     0.983314   
1      5   30     0.702029     1.727361     0.604477     0.795381   
2      5   60     0.660330     1.848286     0.644271     0.809338   
3      5   90     0.733149     1.759387     0.777081     0.772522   

    I/V_Ni222_1  I/V_Ni400_1  I/V_Ni331_1  I/V_Ni420_1  I/V_Ni422_1  \
0      0.809388     1.424946     0.601256     0.699247     0.637840   
12     0.859583     1.488942     0.796039     0.693231     1.053056   
1      0.681152     1.705310     0.636809     0.706412     0.791649   
2      0.669732     1.871940     0.581240     0.743365     0.701569   
3      0.779609     1.789216     0.569585     0.776940     0.805704   

    I/V_Ni511_1  
0      1.009798  
12     0.981382  
1      0.879390  
2      1.132545  
3      1.133505

format the data into their a111, a200, a220, a311 and a222 arrays

In [7]:
o_handler.interpolation()

(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)
(13,)


In [15]:
a1 = np.array(o_handler.a111_interpolated)

In [16]:
a1[1,:]

array([0.84287312, 0.81939913, 0.79592514, 0.77245115, 0.74897716,
       0.72550317, 0.70202918, 0.69507933, 0.68812948, 0.68117964,
       0.67422979, 0.66727994, 0.66033009, 0.67246659, 0.68460309,
       0.69673959, 0.70887608, 0.72101258, 0.73314908, 0.7414312 ,
       0.74971332, 0.75799544, 0.76627756, 0.77455968, 0.78284181,
       0.79179665, 0.80075149, 0.80970633, 0.81866117, 0.82761601,
       0.83657086, 0.84013974, 0.84370863, 0.84727752, 0.85084641,
       0.8544153 , 0.85798419, 0.88796334, 0.91794249, 0.94792164,
       0.97790078, 1.00787993, 1.03785908, 1.04341321, 1.04896735,
       1.05452148, 1.06007561, 1.06562974, 1.07118387, 1.0594005 ,
       1.04761712, 1.03583374, 1.02405036, 1.01226698, 1.0004836 ,
       1.00304999, 1.00561638, 1.00818278, 1.01074917, 1.01331556,
       1.01588195, 1.01131535, 1.00674876, 1.00218216, 0.99761556,
       0.99304896, 0.98848236, 0.96421416, 0.93994595, 0.91567774,
       0.89140953, 0.86714133])

In [8]:
a111_interpolated = o_handler.a111_interpolated
# print(a111_interpolated)
np.shape(a111_interpolated)

(19, 72)

In [9]:
a111 = o_handler.a111
print(a111)
print(np.shape(a111))

[[0.81264008 0.81264008 0.81264008 0.81264008 0.81264008 0.81264008
  0.81264008 0.81264008 0.81264008 0.81264008 0.81264008 0.81264008]
 [0.84287312 0.70202918 0.66033009 0.73314908 0.78284181 0.83657086
  0.85798419 1.03785908 1.07118387 1.0004836  1.01588195 0.98848236]
 [0.94641923 0.7830507  0.66577358 0.69504582 0.66915277 0.76497203
  0.820337   0.89113105 0.91994634 1.04188137 0.99360502 1.02826093]
 [0.92652573 0.93796197 1.00088764 0.79701252 0.73120444 0.63055178
  0.72842354 0.66274537 0.6853093  0.65493447 0.86763136 0.81268304]
 [0.92222536 0.88697934 0.93165715 0.93775382 0.87206267 0.75333254
  0.68154471 0.54400624 0.61929913 0.76592101 0.80907359 0.84883157]
 [1.22723958 1.08306212 0.80485645 0.83218541 0.89863567 1.01121567
  0.97749938 0.87412154 0.84093826 0.86601183 0.87667207 0.83603543]
 [1.35687407 1.4654019  1.09946914 0.71917346 0.89147407 0.81740908
  0.94677943 0.92110097 0.85328919 0.89303171 1.64350745 0.93166034]
 [1.39126485 1.34494245 1.23666602 0.8457

In [10]:
print(a111[3,:])


[0.92652573 0.93796197 1.00088764 0.79701252 0.73120444 0.63055178
 0.72842354 0.66274537 0.6853093  0.65493447 0.86763136 0.81268304]


testing interpolation

In [11]:
yaxis = a111[1,:]
xaxis = np.arange(0,359, 30)

In [12]:
yaxis

array([0.84287312, 0.70202918, 0.66033009, 0.73314908, 0.78284181,
       0.83657086, 0.85798419, 1.03785908, 1.07118387, 1.0004836 ,
       1.01588195, 0.98848236])

In [13]:
new_xaxis = np.array([0, 5,10,15,20,25,30,35,40])

In [16]:
new_xaxis = np.arange(0,359, 5)
len(new_xaxis)

72

In [43]:
from scipy.interpolate import interp1d

In [44]:
f = interp1d(xaxis, yaxis)

In [45]:
f(new_xaxis)

array([0.84287312, 0.81939913, 0.79592514, 0.77245115, 0.74897716,
       0.72550317, 0.70202918, 0.69507933, 0.68812948, 0.68117964,
       0.67422979, 0.66727994, 0.66033009, 0.67246659, 0.68460309,
       0.69673959, 0.70887608, 0.72101258, 0.73314908, 0.7414312 ,
       0.74971332, 0.75799544, 0.76627756, 0.77455968, 0.78284181,
       0.79179665, 0.80075149, 0.80970633, 0.81866117, 0.82761601,
       0.83657086, 0.84013974, 0.84370863, 0.84727752, 0.85084641,
       0.8544153 , 0.85798419, 0.88796334, 0.91794249, 0.94792164,
       0.97790078, 1.00787993, 1.03785908, 1.04341321, 1.04896735,
       1.05452148, 1.06007561, 1.06562974, 1.07118387, 1.0594005 ,
       1.04761712, 1.03583374, 1.02405036, 1.01226698, 1.0004836 ,
       1.00304999, 1.00561638, 1.00818278, 1.01074917, 1.01331556,
       1.01588195, 1.01131535, 1.00674876, 1.00218216, 0.99761556,
       0.99304896, 0.98848236])