## Testing python library

In [29]:
import pandas as pd
import sys, os
import re
import numpy as np
sys.path.insert(0, os.path.abspath('..'))
from project.preparation.vdrive_handler import VDriveHandler

In [5]:
vdrive_filename = '../tests/data/vdrive_filename.txt'
assert os.path.exists(vdrive_filename)

In [6]:
o_vdrive = VDriveHandler()
o_vdrive.load_vdrive(filename=vdrive_filename)
o_vdrive.keep_columns_of_interest()

## Sandbox 

In [28]:
file = '/Users/j35/git/qingge/tests/data/temporary_folder/test_output.txt'

In [32]:
data = pd.read_csv(file)
data.head()

#psi  phi  I/V_Ni111_1  I/V_Ni200_1  I/V_Ni220_1  I/V_Ni311_1  I/V_Ni222_1  \
0     0    0     0.812640     1.452050     0.711520     0.927503     0.809388   
1     5   30     0.702029     1.727361     0.604477     0.795381     0.681152   
2     5   60     0.660330     1.848286     0.644271     0.809338     0.669732   
3     5   90     0.733149     1.759387     0.777081     0.772522     0.779609   
4     5  120     0.782842     1.565342     0.704357     0.755036     0.771645   

   I/V_Ni400_1  I/V_Ni331_1  I/V_Ni420_1  I/V_Ni422_1  I/V_Ni511_1  
0     1.424946     0.601256     0.699247     0.637840     1.009798  
1     1.705310     0.636809     0.706412     0.791649     0.879390  
2     1.871940     0.581240     0.743365     0.701569     1.132545  
3     1.789216     0.569585     0.776940     0.805704     1.133505  
4     1.512697     0.567696     0.684586     0.768479     1.062074

In [33]:
#checking row 0

In [44]:
row_0 = data.iloc[1].values
row_0

array([ 5.        , 30.        ,  0.70202918,  1.72736063,  0.60447731,
        0.79538118,  0.68115197,  1.70530957,  0.63680911,  0.7064115 ,
        0.79164939,  0.87938965])

In [110]:
omega = np.arange(45, 95, 5)
psi = np.arange(0, 50, 5)

hrot1 = list(np.arange(0, 360, 30))
hrot2 = hrot1[::-1]

phi_1 = [0] + list(np.arange(330, 0, -30))
phi_2 = phi_1[::-1]

In [198]:
#bank2

In [199]:
omega = [np.int(_value) for _value in np.ones(12)*45]
hrot1 = np.arange(0, 331, 30)
hrot2 = hrot1[::-1]

In [226]:
hrot2

array([330, 300, 270, 240, 210, 180, 150, 120,  90,  60,  30,   0])

In [202]:
psi_init = np.ones(12) * 90
psi = [np.int(_value) for _value in psi_init]

In [209]:
phia = np.arange(180, -1, -30)
phib = np.arange(330, 180, -30)
phi1 = list(phia) + list(phib)
phi2 = phi1[::-1]

In [238]:
phi1

[180, 150, 120, 90, 60, 30, 0, 330, 300, 270, 240, 210]

In [27]:
a = np.empty((10))
a[:] = np.NaN
a

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [224]:
full_omega = []

omega_offset = np.arange(0, 46, 5)
for _offset in omega_offset:
    full_omega.append(omega + _offset)
    
full_omega = np.reshape(np.transpose(full_omega), 120, 1)
#full_omega

array([45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 80,
       80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 85, 85, 85, 85, 85, 85,
       85, 85, 85, 85, 85, 85, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90,
       90])

In [234]:
full_hrot = []

hrot_offset = 0
while (hrot_offset < 5):
    
    full_hrot.append(hrot1)
    full_hrot.append(hrot2)
    hrot_offset += 1
    
full_hrot = np.reshape(np.transpose(full_hrot), 120, 1)
#full_hrot

120

In [237]:
full_psi = []

psi_offset = np.arange(0, 46, 5)
for _offset in psi_offset:
    full_psi.append(psi - _offset)
    
full_psi = np.reshape(np.transpose(full_psi), 120, 1)
#full_psi

array([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 85, 85, 85, 85, 85,
       85, 85, 85, 85, 85, 85, 85, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80,
       80, 80, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 55,
       55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
       45])

In [239]:
full_phi = []

phi_offset = 0
while (phi_offset < 5):
    
    full_phi.append(phi1)
    full_phi.append(phi2)
    phi_offset += 1
    
full_phi = np.reshape(np.transpose(full_phi), 120, 1)
full_phi

array([180, 150, 120,  90,  60,  30,   0, 330, 300, 270, 240, 210, 210,
       240, 270, 300, 330,   0,  30,  60,  90, 120, 150, 180, 180, 150,
       120,  90,  60,  30,   0, 330, 300, 270, 240, 210, 210, 240, 270,
       300, 330,   0,  30,  60,  90, 120, 150, 180, 180, 150, 120,  90,
        60,  30,   0, 330, 300, 270, 240, 210, 210, 240, 270, 300, 330,
         0,  30,  60,  90, 120, 150, 180, 180, 150, 120,  90,  60,  30,
         0, 330, 300, 270, 240, 210, 210, 240, 270, 300, 330,   0,  30,
        60,  90, 120, 150, 180, 180, 150, 120,  90,  60,  30,   0, 330,
       300, 270, 240, 210, 210, 240, 270, 300, 330,   0,  30,  60,  90,
       120, 150, 180])

In [243]:
value = [2.56048, 2.67035, 2.83892, 2.38051, 2.76638, 2.62911, 2.45172, 2.34996, 2.10361, 1.94961, 2.35532, 2.3631]

In [244]:
import numpy as np

In [245]:
np.std(value)

0.24931523337127273

In [181]:
hrot1 = np.arange(0, 331, 30)
hrot1

array([  0,  30,  60,  90, 120, 150, 180, 210, 240, 270, 300, 330])

In [182]:
hrot2 = hrot1[::-1]
hrot2

array([330, 300, 270, 240, 210, 180, 150, 120,  90,  60,  30,   0])

In [180]:
psi = [np.int(_value) for _value in np.zeros(12)]
psi

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [179]:
phi1 =  phi_1 = [0] + list(np.arange(330, 0, -30))
phi1

[0, 330, 300, 270, 240, 210, 180, 150, 120, 90, 60, 30]

In [183]:
phi2 = phi1[::-1]
phi2

[30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 0]

In [167]:
omega_offset = np.arange(0, 46, 5)
omega_offset

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [178]:
full_omega = []
full_hrot = []
full_psi = []
full_phi = []

for _offset in omega_offset:
    full_omega.append(omega + _offset)
    full_psi.append(psi + _offset)
    
print("omega: {}".format(np.reshape(np.transpose(full_omega), 120, 1)))
print("psi: {}".format(np.reshape(np.transpose(full_psi), 120, 1)))

omega: [45 45 45 45 45 45 45 45 45 45 45 45 50 50 50 50 50 50 50 50 50 50 50 50
 55 55 55 55 55 55 55 55 55 55 55 55 60 60 60 60 60 60 60 60 60 60 60 60
 65 65 65 65 65 65 65 65 65 65 65 65 70 70 70 70 70 70 70 70 70 70 70 70
 75 75 75 75 75 75 75 75 75 75 75 75 80 80 80 80 80 80 80 80 80 80 80 80
 85 85 85 85 85 85 85 85 85 85 85 85 90 90 90 90 90 90 90 90 90 90 90 90]
psi: [ 0  0  0  0  0  0  0  0  0  0  0  0  5  5  5  5  5  5  5  5  5  5  5  5
 10 10 10 10 10 10 10 10 10 10 10 10 15 15 15 15 15 15 15 15 15 15 15 15
 20 20 20 20 20 20 20 20 20 20 20 20 25 25 25 25 25 25 25 25 25 25 25 25
 30 30 30 30 30 30 30 30 30 30 30 30 35 35 35 35 35 35 35 35 35 35 35 35
 40 40 40 40 40 40 40 40 40 40 40 40 45 45 45 45 45 45 45 45 45 45 45 45]


In [197]:
full_hrot = []
full_phi = []
_index = 0
while (_index < 46):
    
    full_hrot.append(hrot1)
    full_phi.append(phi1)
    
    full_hrot.append(hrot2)
    full_phi.append(phi2)
    
    _index += 10
  
print("hrot: {}".format(np.reshape(np.transpose(full_hrot), 10*12, 1)))
print("phi: {}".format(np.reshape(np.transpose(full_phi), 10*12, 1)))

hrot: [  0  30  60  90 120 150 180 210 240 270 300 330 330 300 270 240 210 180
 150 120  90  60  30   0   0  30  60  90 120 150 180 210 240 270 300 330
 330 300 270 240 210 180 150 120  90  60  30   0   0  30  60  90 120 150
 180 210 240 270 300 330 330 300 270 240 210 180 150 120  90  60  30   0
   0  30  60  90 120 150 180 210 240 270 300 330 330 300 270 240 210 180
 150 120  90  60  30   0   0  30  60  90 120 150 180 210 240 270 300 330
 330 300 270 240 210 180 150 120  90  60  30   0]
phi: [  0 330 300 270 240 210 180 150 120  90  60  30  30  60  90 120 150 180
 210 240 270 300 330   0   0 330 300 270 240 210 180 150 120  90  60  30
  30  60  90 120 150 180 210 240 270 300 330   0   0 330 300 270 240 210
 180 150 120  90  60  30  30  60  90 120 150 180 210 240 270 300 330   0
   0 330 300 270 240 210 180 150 120  90  60  30  30  60  90 120 150 180
 210 240 270 300 330   0   0 330 300 270 240 210 180 150 120  90  60  30
  30  60  90 120 150 180 210 240 270 300 330   0]


In [72]:
hrot_full = hrot + hrot_reversed
hrot_full


[0,
 30,
 60,
 90,
 120,
 150,
 180,
 210,
 240,
 270,
 300,
 330,
 330,
 300,
 270,
 240,
 210,
 180,
 150,
 120,
 90,
 60,
 30,
 0]

In [78]:
phi_1 = list(np.arange(330, 0, -30))
phi_2 = phi_1[::-1]
phi = [0] + list(phi_1) + list(phi_2) + [0]
phi

[0,
 330,
 300,
 270,
 240,
 210,
 180,
 150,
 120,
 90,
 60,
 30,
 30,
 60,
 90,
 120,
 150,
 180,
 210,
 240,
 270,
 300,
 330,
 0]

In [11]:
o_vdrive_data = o_vdrive.data.raw

In [13]:
names_of_columns = o_vdrive_data.columns.values

In [51]:
bank1_string = r'^\w*/\w*_\w*_1$'

In [49]:
_label_0 = names_of_columns[0]
print(_label_0)

I/V_Ni111_1


In [50]:
m_bank1 = re.match(bank1_string, _label_0)
print(m_bank1)

None


In [9]:
from collections import namedtuple

In [12]:
Filenames = namedtuple('Filenames', ['bank1','bank2'])

In [21]:
my_file = Filenames(bank1=[1,2,3], bank2=None)

In [24]:
my_file.bank1 = [3,4,5]

AttributeError: 'Filenames' object attribute 'bank1' is read-only

In [14]:
my_file.bank1 = [1,2,3]

In [19]:
my_file.bank1

[1, 2, 3]

In [15]:
my_file.bank = [3,4,5]

TypeError: 'type' object does not support item assignment

In [6]:
import pandas as pd
import numpy as np
import re

In [15]:
pd_data = pd.read_csv(vdrive_filename, sep='\t', index_col=0)

In [16]:
pd_data.head()

GoodFit_Ni111_1  ChiSq_Ni111_1  d_Ni111_1  ed_Ni111_1  Tof_Ni111_1  \
Run                                                                           
78901.0              1.0           6.01   2.077895    0.000137      34.0123   
78902.0              1.0           6.27   2.078163    0.000139      34.0167   
78903.0              1.0           7.68   2.078849    0.000156      34.0279   
78904.0              1.0           5.96   2.078996    0.000152      34.0303   
78905.0              1.0           5.72   2.078901    0.000134      34.0288   

         eTof_Ni111_1  I/V_Ni111_1  eI/V_Ni111_1  I/V1_Ni111_1  eI/V1_Ni111_1  \
Run                                                                             
78901.0      0.002245      2.56048      0.055237       2.56048       0.055237   
78902.0      0.002276      2.67035      0.057442       2.67035       0.057442   
78903.0      0.002551      2.83892      0.065576       2.83892       0.065576   
78904.0      0.002481      2.38051      0.053063       2.38051       0.053063   
78905.0      0.002190      2.76638      0.055741       2.76638       0.055741   

              ...         B/V_Ni511_2  eB/V_Ni511_2  Sig^2_Ni511_2  \
Run           ...                                                    
78901.0       ...            0.000928      0.000028        909.505   
78902.0       ...            0.000945      0.000026        857.585   
78903.0       ...            0.000929      0.000022        885.386   
78904.0       ...            0.000793      0.000020        841.615   
78905.0       ...            0.000741      0.000023        888.970   

         eSig^2_Ni511_2  Gam_Ni511_2  eGam_Ni511_2  FWHM_Ni511_2  \
Run                                                                
78901.0           64.57      14.2229           0.0      0.004810   
78902.0           53.62      12.6591           0.0      0.004631   
78903.0           52.60      12.5202           0.0      0.004694   
78904.0           60.88      12.6364           0.0      0.004591   
78905.0           62.07      15.0035           0.0      0.004787   

         eFWHM_Ni511_2  Strain_Ni511_2  eStrain_Ni511_2  
Run                                                      
78901.0       0.000154        0.000000         0.000123  
78902.0       0.000132       -0.000166         0.000115  
78903.0       0.000127       -0.000189         0.000113  
78904.0       0.000151       -0.000232         0.000121  
78905.0       0.000150       -0.000331         0.000120  

[5 rows x 400 columns]

In [17]:
# keeping only the I/V.. and eI/V.. columns

In [22]:
name_of_columns = pd_data.columns.values

In [38]:
re_string = r'^I/V_\w*$'

columns_I_V = []
columns_eI_V = []
columns_to_keep = []
for _index, _label in enumerate(name_of_columns):
    m = re.match(re_string, _label)
    if m:
        columns_I_V.append(_index)
        columns_eI_V.append(_index+1)
        columns_to_keep.append(pd_data.columns.values[_index])
        columns_to_keep.append(pd_data.columns.values[_index+1])
        

In [40]:
data_to_keep = pd_data.filter(columns_to_keep)

In [41]:
data_to_keep


I/V_Ni111_1  eI/V_Ni111_1  I/V_Ni200_1  eI/V_Ni200_1  I/V_Ni220_1  \
Run                                                                          
78901.0      2.56048      0.055237     2.725390      0.067528     0.857533   
78902.0      2.67035      0.057442     2.114000      0.044217     0.843077   
78903.0      2.83892      0.065576     2.002980      0.043415     0.706890   
78904.0      2.38051      0.053063     1.882990      0.042507     0.794349   
78905.0      2.76638      0.055741     2.181890      0.049217     0.805260   
78906.0      2.62911      0.060967     2.488100      0.060878     0.924830   
78907.0      2.45172      0.056449     2.447750      0.055581     0.910975   
78908.0      2.34996      0.048634     2.270570      0.051359     0.888381   
78909.0      2.10361      0.053184     2.465580      0.050196     0.827032   
78910.0      1.94961      0.043943     2.446200      0.052087     0.867460   
78911.0      2.35532      0.051827     2.721960      0.056610     0.833332   
78912.0      2.36310      0.049686     3.046000      0.065196     0.836102   
78913.0      1.95495      0.040685     2.634780      0.059826     0.659718   
78914.0      1.83883      0.041530     2.819230      0.063018     0.703148   
78915.0      2.04161      0.045506     2.683630      0.058849     0.848095   
78916.0      2.17999      0.050568     2.387650      0.052075     0.768725   
78917.0      2.32961      0.053191     2.440510      0.051979     0.742087   
78918.0      2.38924      0.057807     2.573150      0.054827     0.847994   
78919.0      2.89014      0.067349     2.579290      0.058064     0.832909   
78920.0      2.98294      0.061769     1.756580      0.036775     0.691524   
78921.0      2.78606      0.063649     1.732720      0.037771     0.646546   
78922.0      2.82894      0.063166     1.902940      0.039062     0.737845   
78923.0      2.75264      0.060201     2.071100      0.041061     0.905258   
78924.0      2.34716      0.054728     2.325910      0.052494     0.688289   
78925.0      2.46464      0.052877     2.114020      0.046600     1.001680   
78926.0      2.67777      0.061360     2.217390      0.045117     0.920306   
78927.0      2.58752      0.060390     2.020370      0.040143     0.913347   
78928.0      2.71324      0.062613     1.988700      0.042983     0.749657   
78929.0      2.39570      0.056635     1.751790      0.036112     0.770211   
78930.0      2.32066      0.050261     1.784980      0.039371     0.540265   
...              ...           ...          ...           ...          ...   
78991.0      2.33967      0.054351     0.891383      0.020451     0.927154   
78992.0      2.04623      0.045182     0.950616      0.023373     1.532280   
78993.0      2.25995      0.048899     1.152180      0.028678     0.856198   
78994.0      2.95748      0.077119     1.302040      0.027458     1.047910   
78995.0      2.58817      0.062508     0.829748      0.019110     1.504830   
78996.0      3.01365      0.071277     0.790788      0.019141     1.442530   
78997.0      3.01449      0.073002     0.967774      0.021242     1.132130   
78998.0      3.00730      0.069854     0.760490      0.018094     1.702830   
78999.0      3.14790      0.068657     0.984665      0.022869     1.040990   
79000.0      3.20691      0.066378     1.086030      0.027053     0.865294   
79001.0      2.57198      0.059603     0.933673      0.021271     1.725600   
79002.0      2.08487      0.042599     0.876403      0.022122     1.124630   
79003.0      2.40316      0.056473     0.734121      0.017022     0.605702   
79004.0      2.03439      0.049444     1.064480      0.025919     0.781768   
79005.0      2.99483      0.077835     0.851462      0.020666     1.009280   
79006.0      2.48640      0.058496     0.751736      0.016337     0.869353   
79007.0      2.40525      0.052610     0.761248      0.019280     0.986925   
79008.0      3.30427      0.071766     1.504830      0.035261     1.052890   
79009.0      3.17624      0.075